apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: site-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: site-volume
          persistentVolumeClaim:
            claimName: static-site-pvc
